import { useScroll, useTransform, motion } from "framer-motion";
import type { NextPage } from "next";
import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  Branding,
  Navbar,
  Header,
  Info,
  Title,
  PrimaryButton,
  Heading,
  Battle,
} from "../src/components/index";
import { getProviders, getSession, signIn } from "next-auth/react";

interface LoginProps {
  providers: {
    id: string;
    name: string;
  }[];
}

const Login: NextPage<LoginProps> = ({ providers }) => {
  return (
    <>
      <Head>
        <title>Superhero Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <header className="h-[calc(100vh-80px)] bg-primary-500 flex flex-row px-4 sm:px-0">
        <div className="h-full w-full sm:w-[50%] lg:w-[30%] grid place-content-center">
          <div className="bg-white py-4 px-8 rounded-md flex flex-col items-center">
            <Heading title="Login" color="text-primary-500" />
            <div className="py-4" />
            {providers &&
              Object.values(providers).map((provider) => (
                <button
                  key={provider.id}
                  onClick={() => signIn(provider.id)}
                  className="bg-primary-500 hover:bg-primary-300 active:bg-primary-700 text-slate-50 px-6 py-2 text-xl font-primary rounded-md flex flex-row items-center space-x-2"
                >
                  <Image
                    src="/images/google.svg"
                    alt="Google Icon"
                    width={24}
                    height={24}
                    objectFit="cover"
                    priority={true}
                  />
                  <span>Sign in with {provider.name}</span>
                </button>
              ))}
          </div>
        </div>
        <div className="w-0 sm:w-[50%] lg:w-[70%] h-full login-header bg-no-repeat bg-cover bg-[url('/images/login-bg.jpg')]"></div>
      </header>
    </>
  );
};

export default Login;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const providers = await getProviders();
  const { req } = context;
  const Session = await getSession({ req: req });

  if (Session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      providers,
    },
  };
};
