import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Battle: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-primary">Battles</h1>
      </main>
    </>
  );
};

export default Battle;
